apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
      - name: default-ipv4-ippool
        cidr: 192.168.0.0/16   # must match podSubnet in kind-cluster.yaml
        blockSize: 26
        encapsulation: VXLAN   # works on Kind (no BGP/IPIP needed)
        natOutgoing: Enabled
        nodeSelector: all()
