apiVersion: v1
kind: Service

metadata:
  name: gateway-service
  labels:
    app.kubernetes.io/name: llm-gateway
    app.kubernetes.io/part-of: llm-platform

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: llm-gateway
    app.kubernetes.io/instance: gateway

  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
