apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: ollama-pvc
  namespace: llm

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: manual

  resources:
    requests:
      storage: 15Gi
