apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm

resources:
  - namespace.yaml
  - storage/persistent-volume.yaml
  - storage/persistent-volume-claim.yaml
  - deployments/ollama-deployment.yaml
  - services/ollama-service.yaml
  - deployments/fastapi-deployment.yaml
  - services/fastapi-service.yaml
  - configmaps/fastapi-config.yaml
