from prometheus_client import Counter, Histogram

REQUEST_COUNTER = Counter(
    "http_requests_total",
    "Total HTTP Requests",
    ["method", "path", "status_code"],
)

REQUEST_LATENCY = Histogram(
    "http_requests_duration_seconds",
    "HTTP request latency in seconds",
    labelnames=["method", "path"],
    buckets=(0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15, 30, 60, 120),
)

GENERATED_TOKENS = Counter(
    "llm_generated_tokens_total",
    "Total tokens generated by the model (Ollama eval_count)",
)

TOKENS_PER_SECOND = Histogram(
    "llm_tokens_per_second",
    "Generation speed per request (eval_count / eval_duration)",
    buckets=(0.5, 1, 2, 3, 5, 7.5, 10, 15, 20, 30, 50, 100),
)
